name: Deploy Rick and Morty API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Kubeconfig (from GitHub secret)
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube  # יצירת תיקיית .kube אם היא לא קיימת
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config  # הוספת ה-Kubeconfig

    # 3. Install Helm
    - name: Install Helm
      run: |
        curl https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz -o helm.tar.gz
        tar -zxvf helm.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm

    # 4. Deploy using Helm
    - name: Deploy with Helm
      run: |
        helm upgrade --install rick-and-morty-api ./helm/rick-and-morty-api --namespace default --create-namespace

    # 5. Wait for pods to be ready
    - name: Wait for pods to be ready
      run: |
        kubectl wait --for=condition=ready pod -l app=rick-and-morty-api --timeout=300s

    # 6. Test the healthcheck endpoint
    - name: Test Healthcheck Endpoint
      run: |
        curl -X GET http://rick-and-morty.local/healthcheck
