   name: Deploy Rick and Morty API
   
   on:
     push:
       branches:
         - main
   jobs:
     deploy:
       runs-on: [self-hosted, oded1]

       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup kubectl
           uses: azure/setup-kubectl@v3
           with:
             version: 'latest'

         - name: Install Minikube
           run: |
             curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
             chmod +x minikube
             sudo mv minikube /usr/local/bin/
             minikube start --driver=docker

         - name: Set up Helm
           uses: azure/setup-helm@v3
           with:
             version: 'v3.12.0'

         - name: Build Docker image
           run: |
             docker build -t rick-and-morty-api:latest .
             minikube image load rick-and-morty-api:latest

         - name: Deploy Helm Chart
           run: |
             helm install rick-and-morty-api ./helm/rick-and-morty-api --set image.repository=rick-and-morty-api --set image.tag=latest

         - name: Test Application
           run: |
             sleep 30  # Wait for pods to be ready
             curl -X GET http://rick-and-morty.local/healthcheck
